Parse email utf8 8bit
demisto/parse-emails pull request #92
Opened 2024-08-07 10:16 UTC by maimorag

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-7599)

## Description
fix utf-8 with 8 bit

2024-08-11 08:03 UTC, yaakovpraisler approved these changes

2024-08-11 13:23 UTC, eyalpalo requested changes
Nice
Can you attach a screenshot of the test failing with the same error as in the bug before your fix?

2024-08-11 13:23 UTC, eyalpalo commented on parse_emails/tests/parse_emails_test.py
> +    expected_response = '这是一个示例邮件，用于演示指定的条件。\r\n它使用了 UTF-8 编码，可以支持多种语言的字符，包括中文。\r\n祝好，\r\n发件人'
do we have another place in the repo with Chinese letters?

2024-08-12 09:39 UTC, maimorag commented
failed test without the fix:
![image](https://github.com/user-attachments/assets/da4ecd91-5f19-4276-a418-496a7f538aff)
 
 please notice how decode_content returns the following:
  `'\\u8fd9\\u662f\\u4e00\\u4e2a\\u793a\\u4f8b\\u90ae\\u4ef6\\uff0c\\u7528\\u4e8e\\u6f14\\u793a\\u6307\\u5b9a\\u7684\\u6761\\u4ef6\\u3002\r\n\\u5b83\\u4f7f\\u7528\\u4e86 UTF-8 \\u7f16\\u7801\\uff0c\\u53ef\\u4ee5\\u652f\\u6301\\u591a\\u79cd\\u8bed\\u8a00\\u7684\\u5b57\\u7b26\\uff0c\\u5305\\u62ec\\u4e2d\\u6587\\u3002\r\n\\u795d\\u597d\\uff0c\r\n\\u53d1\\u4ef6\\u4eba'`
  
  instead of:
  `'这是一个示例邮件，用于演示指定的条件。\r\n它使用了 UTF-8 编码，可以支持多种语言的字符，包括中文。\r\n祝好，\r\n发件人'`

2024-08-12 13:34 UTC, eyalpalo approved these changes

2024-08-12 13:38 UTC, merged